# Generated by Django 3.1.3 on 2021-03-07 00:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.CharField(blank=True, max_length=2, null=True)),
                ('cue', models.CharField(blank=True, max_length=7, null=True)),
                ('nombre', models.CharField(blank=True, max_length=47, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=55, null=True)),
                ('turno', models.CharField(blank=True, max_length=5, null=True)),
                ('localidad', models.CharField(blank=True, max_length=23, null=True)),
                ('porcentaje_zona', models.CharField(blank=True, max_length=5, null=True)),
                ('zona', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': 'false',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(default='Argentino', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='gestionescuelas.persona')),
                ('codigo_unico_alumno', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumno_persona_id', serialize=False, to='gestionescuelas.persona')),
            ],
            bases=('gestionescuelas.persona',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionescuelas.persona')),
                ('relacion', models.CharField(default='Tutor', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('documentacion', models.BooleanField(default=False)),
                ('nivel_educativo', models.CharField(default='Primario', max_length=100)),
                ('codigo_inscripcion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('curso', models.CharField(max_length=30)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.institucion')),
                ('alummno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.tutor')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
