# Generated by Django 3.1.3 on 2021-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.CharField(blank=True, max_length=2, null=True)),
                ('cue', models.CharField(blank=True, max_length=7, null=True)),
                ('nombre', models.CharField(blank=True, max_length=47, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=55, null=True)),
                ('turno', models.CharField(blank=True, max_length=5, null=True)),
                ('localidad', models.CharField(blank=True, max_length=23, null=True)),
                ('porcentaje_zona', models.CharField(blank=True, max_length=5, null=True)),
                ('zona', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': 'false',
            },
        ),
    ]
