# Generated by Django 3.1.3 on 2021-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('cue', models.BigIntegerField(null=True)),
                ('anexo', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=30)),
                ('ambito', models.CharField(max_length=80)),
                ('zona_supervision', models.CharField(max_length=80)),
                ('oferta_tipo', models.CharField(max_length=133)),
                ('localidad', models.CharField(max_length=80)),
                ('departamento', models.CharField(max_length=128)),
                ('domicilio', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'escuelasprimarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
