# Generated by Django 3.1.3 on 2021-02-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.CharField(blank=True, max_length=2, null=True)),
                ('cue', models.CharField(blank=True, max_length=7, null=True)),
                ('nombre', models.CharField(blank=True, max_length=47, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=55, null=True)),
                ('turno', models.CharField(blank=True, max_length=5, null=True)),
                ('localidad', models.CharField(blank=True, max_length=23, null=True)),
                ('porcentaje_zona', models.CharField(blank=True, max_length=5, null=True)),
                ('zona', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='name',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='escuela',
            table='escuelas_primarias',
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.persona')),
            ],
        ),
    ]
