# Generated by Django 3.1.3 on 2021-03-07 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('documentacion', models.BooleanField(default=False)),
                ('nivel_educativo', models.CharField(default='Primario', max_length=100)),
                ('codigo_inscripcion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('curso', models.CharField(max_length=30)),
                ('alummno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.alumno')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.institucion')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionescuelas.tutor')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
