# Generated by Django 3.1.3 on 2021-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0002_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
