# Generated by Django 3.1.3 on 2021-02-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0002_auto_20210211_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(default='Argentino', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
