# Generated by Django 3.1.3 on 2021-03-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0003_auto_20210307_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='alummno',
            new_name='alumno',
        ),
    ]
