# Generated by Django 3.1.3 on 2021-02-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionescuelas', '0003_auto_20210211_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
